services:
  postgres:
    image: postgres:16.3-alpine
    container_name: originalUrl-shortener-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: UTC
      PGTZ: UTC
    ports:
      - "127.0.0.1:${POSTGRES_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - local-net

  redis:
    image: redis:7.2-alpine
    container_name: originalUrl-shortener-redis
    ports:
      - "127.0.0.1:${REDIS_PORT}:6379"
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - local-net

  localstack:
    image: localstack/localstack:3.0.0
    container_name: originalUrl-shortener-aws
    ports:
      - "127.0.0.1:${LOCALSTACK_PORT}:4566"
    environment:
      SERVICES: dynamodb,sqs,ses
      DEFAULT_REGION: ${AWS_REGION}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      LOCALSTACK_ENDPOINT_URL: http://localhost:4566
      SES_FROM_EMAIL: ${SES_FROM_EMAIL:-no-reply@url-shortener.local}
      URL_TABLE_NAME: ${DYNAMODB_URL_TABLE_NAME}
      COUNTER_TABLE_NAME: ${DYNAMODB_URL_COUNTER_TABLE_NAME}
      URL_COUNTER_NAME: url_short_code
      URL_REDIRECT_EVENTS_QUEUE_NAME: ${SQS_URL_REDIRECT_EVENTS_QUEUE_NAME}
      URL_REDIRECT_EVENTS_DLQ_NAME: ${SQS_URL_REDIRECT_EVENTS_DLQ_NAME}
      EMAIL_VERIFICATION_EVENTS_QUEUE_NAME: ${SQS_EMAIL_VERIFICATION_EVENTS_QUEUE_NAME}
      EMAIL_VERIFICATION_EVENTS_DLQ_NAME: ${SQS_EMAIL_VERIFICATION_EVENTS_DLQ_NAME}
    volumes:
      - ./localstack-init:/etc/localstack/init/ready.d
    networks:
      - local-net

networks:
  local-net:
    driver: bridge

volumes:
  postgres-data:
