spring:
  config:
    import: aws-secretsmanager:/url-shortener/dev/application

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${postgres.password}

  cloud:
    aws:
      endpoint: ${LOCALSTACK_ENDPOINT_URL}

      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}

      region:
        static: ${AWS_REGION}

      sqs:
        queue-not-found-strategy: fail

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
    show-sql: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  flyway:
    enabled: true

aws:
  dynamodb:
    endpoint: ${LOCALSTACK_ENDPOINT_URL}
    region: ${AWS_REGION}
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
    tables:
      url: ${DYNAMODB_URL_TABLE_NAME}
      url-counter: ${DYNAMODB_URL_COUNTER_TABLE_NAME}

app:
  base-url: ${APP_BASE_URL}

  openapi:
    enabled: ${APP_OPENAPI_ENABLED:true}

  iam:
    email-verification:
      ses:
        endpoint: ${LOCALSTACK_ENDPOINT_URL}

  outbox:
    sqs:
      queues:
        EMAIL_VERIFICATION_REQUESTED: ${SQS_EMAIL_VERIFICATION_EVENTS_QUEUE_NAME}

  aws:
    sqs:
      url-redirect-events-queue: ${SQS_URL_REDIRECT_EVENTS_QUEUE_NAME}
      url-redirect-events-dlq: ${SQS_URL_REDIRECT_EVENTS_DLQ_NAME}
      email-verification-events-queue: ${SQS_EMAIL_VERIFICATION_EVENTS_QUEUE_NAME}
      email-verification-events-dlq: ${SQS_EMAIL_VERIFICATION_EVENTS_DLQ_NAME}

logging:
  level:
    org.hibernate.orm.jdbc.error: OFF
